version: '3.5'

services:
  nexus:
    container_name: nexus3
    platform: linux/x86_64
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "9001:8081"

volumes:
  nexus-data: {}